#pragma once
void Divide();
void Divide2();
void Default(Computer**&);
void Add(Computer**&);
void Change(Computer**&);
void Delete(Computer**&);
Computer** Menu(Computer**&);
void Menu2(Computer**&);
void Menu3(Computer**&);
void Title();
void Title2();
void In(fstream& ,Computer**&);
void Show(Computer**&,bool Flag=true);
void Save(Computer**&,bool Flag=true);
void ToDouble(double&);
void ToInt(int&);
void ToTime(string&);
bool CheckInt(int&,string,int min=-1,int max=-1);
bool Back(Computer**&);
void FindComponent(Computer**&);
void FindShow(Computer**&,int*&,int);
void FindPrice(Computer**&);
void FindType(Computer**&);
void FindClass(Computer**&);
void FindManufacturer(Computer**&);
void FindTime(Computer**&);
void FindChange(Computer**&,int*&,int);
void OrderComponent(Computer**&);
void OrderPrice(Computer**&);
void OrderType(Computer**&);
void OrderClass(Computer**&);
void OrderManufacturer(Computer**&);
void OrderTime(Computer**&);